name: UI checks
run-name: ${{ github.actor }} is linting, formating and testing
on:
  workflow_call:
  pull_request:
    branches:
      - 'main'
jobs:
  lint-format:
    name: Lint 🔎, Format ✅, Test 🧪
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/hydrogen

      - name: Install pnpm
        shell: bash
        id: pnpm-install
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: run format ✅
        run: pnpm run format

      - name: run linter 🔎
        run: pnpm run lint

      - name: run tests 🧪
        run: pnpm test
